### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by alejandraR22**
sign in

### CODE REVIEW

**Comment by alejandraR22** [comment]
alejandra part

**Comment by akga20052** [comment]
it looks good girl. I know you wanted me to give you my personal feed back 

MY TIP: 
A. space btw the username, email, and password
b. I love how you included the words username, email and password. It was not located on the picture but good idea xoxox

C. space btw the little social platform icons..

OTHER THEN that I LOVE IT great job!!!!

**Review by akga20052 — COMMENTED** [review]
aww you didnt have to change it cause I give you a tip, but it is good practice in github for both of us commenting on stuff lol

**Review by akga20052 — COMMENTED** [review]
thanks for the update

**Pull request merged**
